version: '3.2'

services:
  
  influxdb:
    image: influxdb:1.8-alpine
    env_file: ./.env
    volumes:
      - ./:/imports
      - ./influxdb_data:/var/lib/influxdb
    ports:
      - "8060:8060"

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "472"
    ports:
      - "13001:3000"
    depends_on:
      - influxdb
    env_file:
      - ./.env

    volumes:
      - './grafana/provisioning/:/etc/grafana/provisioning/'
      - 'grafana_data:/var/lib/grafana'

  telegraf:
    build: './telegraf'
    container_name: telegraf
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    env_file:
      - ./.env

volumes:
    grafana_data: {}
